version: '3.9'

services:
 backend:
    restart: "no"
    container_name: backend
    hostname: backend
    build:
      dockerfile: backend/Dockerfile
    command: sh -c "python backend/main.py"
    volumes:
      - ./:/AI-QA-Helper
    ports:
      - '85:8000'

 bot_ai:
    restart: "no"
    container_name: bot_ai
    build:
      dockerfile: bot/Dockerfile
    command: sh -c "python bot/telegram_bot.py"
    volumes:
      - ./:/TG_bot
    depends_on:
      - backend 

 frontend:
    restart: "no"
    container_name: frontend_ai
    hostname: frontend
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80" 
    environment:
      - NODE_ENV=production 
    depends_on:
      - backend 