version: '3.9'

services:
 backend:
   restart: "no"
   hostname: backend
   container_name: backend
   build:
     dockerfile: backend/Dockerfile
   command: sh -c "python main.py"
   volumes:
     - ./:/AI-QA-Helper
   ports:
     - '85:8000'

  # bot_ai:
  #   restart: "no"
  #   build:
  #     dockerfile: bot/Dockerfile
  #   command: sh -c "python bot/telegram_bot.py"
  #   container_name: bot_ai
  #   volumes:
  #     - ./:/TG_bot